---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-apps 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: applications-project
  source:
    repoURL: git@github.com:yiuc/eks-gitops-crossplane-argocd.git
    targetRevision: HEAD
    path: workload-apps
    helm:
      values: |
        spec:
          destination:
            server: https://D61A5789E895B3B38F6626E00F74FEC8.gr7.us-west-2.eks.amazonaws.com       
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true    