#
# ArgoCD App of Apps used to deploy all Crossplane related resources to the management ckuster.
# This includes the Crossplane core controller, AWS provider for Crossplane, Configuration package containing Composition, CompositeResourceDefinition and CompositeResource.
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-eks 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: workloads-project
  source:
    repoURL: git@github.com:yiuc/eks-gitops-crossplane-argocd.git
    targetRevision: HEAD
    path: crossplane-prod-ready/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: team-b
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m   
