apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  encryptedData:
    credentials: AgCTYeEO+keMEe1L8VY9n7l29FohC0AF1gskevjqjEFKNGgSVL9HjLocQbfIuJ93ZYfQT8s3eyAB+iYYinH10dAkVlbdpPLCYOuY9YAMgthHG97DLhBMwfz/tYjsBEVl8S9WTbNWcNLs3dHcoKC4p1U7Mx5CQb0uFSoIE8wxk3K5I0rDJwvjzjoQBoqprNybC6mw2B+Vhh0nEy6PNGPAqunNBJ+5nQxJU3KADPED0kLj11R9QHRjxrgGTvesX0K0fFYrzWeVmSSuw/3FK1fbgAjOxaUUVmZm8hd0uZB5PtQx5NbfBT2/cff9Fpl2XsluVaaH2oZe6evUqGg9EYjGoDypgR2RmeIWf6dsNLnpK8KCpVyCeYhwodHAdPB4M2PthnnrJMz5U8HH4ZfLKELZwwp6DmE/gFzP26YjIFlmWdWs0GqSt+MR/EKB81YAMyRrgdwP7F04/+MzrTpRkG5aSnatVED23KSeb5xzAZosTxypwoiDCnqnN34iIMfFa0art4hE3hx/AR3cNFBCh0Z25z8Vu3c+dyUOM7xagKr9Ai1I4T1tj0oUxMt5ez73p+jYvIpA7ePZxrttk5eMj55fnYjw/AVj4zwv4U+VNcdTJBGHu6ZaXZf5oZP8d4hyp2R6naYYhtR7Dn683rJszaYTEWDzjtd5nhRSSlGb8CGN4eMipRlyGU4pklgxo3o8G15+1HeXkU/rNHlka5ap+mEyQ2OjUqAJo3azGIj6ltVm8JzZyux8bdtwXCUMyxlqtcYkAkx3PD/TmjSceY1Mn29XQ71uFJnoMKpPM27oap2JbUJaGDsC5hAkOvMGL2lG6K206/7ynZAGt6rHT13hKkUBp0cO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

