---
apiVersion: eks.sarathy.io/v1beta1
kind: EKSCluster
metadata:
  name: crossplane-argocd-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "300"   
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true    
spec:
  parameters:
    region: ap-southeast-1
    vpc-name: "EKS-CROSSPLANE-ARGOCD-VPC"
    vpc-cidrBlock: "192.168.48.0/20"

    subnet1-public-name: "PUBLIC-WORKER-1"
    subnet1-public-cidrBlock: "192.168.48.0/24"
    subnet1-public-availabilityZone: "ap-southeast-1a"
    
    subnet2-public-name: "PUBLIC-WORKER-2"
    subnet2-public-cidrBlock: "192.168.49.0/24"
    subnet2-public-availabilityZone: "ap-southeast-1b"    

    subnet1-private-name: "PRIVATE-WORKER-1"
    subnet1-private-cidrBlock: "192.168.50.0/24"
    subnet1-private-availabilityZone: "ap-southeast-1a"
    
    subnet2-private-name: "PRIVATE-WORKER-2"
    subnet2-private-cidrBlock: "192.168.51.0/24"
    subnet2-private-availabilityZone: "ap-southeast-1b"     

    cluster-role: arn:aws:iam::928262269243:role/eksctl-crossplane-blueprints-cluster-ServiceRole-18KZDISKT2GA0
    workernode-role: arn:aws:iam::928262269243:role/eksctl-crossplane-blueprints-node-NodeInstanceRole-10TJ9AILEGKD8

    k8s-version: "1.21"
    workload-type: "non-gpu"
    workers-size: 2

  compositionRef:
    name: amazon-eks-cluster

  writeConnectionSecretToRef:
    namespace: eks
    name: crossplane-argocd-cluster-connection